# Site settings
baseURL = "https://www.vrany.dev"
languageCode = "en-US"
title = "Stepan Vrany | Cloud and Automation Engineer"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2019 Stepan Vrany"

[params]

  # Metadata for search engines and social sharing
  author = "Stepan Vrany"
  description = "Stepan is Cloud and Automation engineer focused on Developer Experience and simplicity. Available for hire :) Favorite technologies: AWS, Kubernetes, Helm, Open Policy Agent, Gitlab CI, Golang"
  shareImage = "/static/stepan.jpg"
  twitterHandle = "MstrsObserver"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "/static/stepan.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://www.blog.vrany.dev"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:vrany.stepan@protonmail.com"

      #[[params.links.list1.link]]
      #  text = "Newsletter"
      #  url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/MstrsObserver"

      [[params.links.list2.link]]
        text = "LinkedIN"
        url = "https://www.linkedin.com/in/stepanvrany/"

      [[params.links.list2.link]]
        text = "Stack overflow"
        url = "https://stackoverflow.com/users/1410268/stepan-vrany"

  [[params.links]]
    [params.links.list2]
      heading = "Lost&Found"

      [[params.links.list2.link]]
        text = "About"
        url = "/about/"

